name: wt_versus
description: War Thunder Versus 3

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.1+301

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #State management
  provider: ^6.0.1
  #Firebase
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.7
  firestore_cache: ^2.2.0
  firebase_auth: ^3.3.11
  firebase_crashlytics: ^2.5.3
  #Sign-In
  google_sign_in: ^5.2.4
  sign_in_with_apple: ^3.3.0
  crypto: ^3.0.1
  #Ads
  google_mobile_ads: ^1.1.0
  app_tracking_transparency: ^2.0.2+1
  #Icons
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  flutter_svg: ^0.22.0
  #Feedback screen
  package_info_plus: ^1.0.6
  device_info_plus: ^3.2.1
  url_launcher: ^6.0.10
  in_app_review: ^2.0.3
  share_plus: ^3.0.0
  #Miscellaneous
  introduction_screen: ^3.0.0
  persistent_bottom_nav_bar: ^4.0.2
  truncate: ^3.0.1
  intl: ^0.17.0
  google_fonts: ^2.1.1
  shared_preferences: ^2.0.7
  marquee: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.1
  change_app_package_name: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/icon.png
  fullscreen: true
  android: true
  ios: true

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Symbols
      fonts:
        - asset: assets/fonts/symbols_skyquake.ttf
